"""removed due_date column to Task

Revision ID: 7b4d4d9bdab5
Revises: 3caf5e48d10b
Create Date: 2025-11-21 12:56:58.502126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b4d4d9bdab5'
down_revision: Union[str, Sequence[str], None] = '3caf5e48d10b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'due_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
